public enum EventType
{
	UNLOCK_STAIR_NORTH,
	UNLOCK_STAIR_WEST,
	UNLOCK_NEXT_LEVEL,
	UNLOCK_LIFT,
	DOOR_OPENED,
	DOOR_CLOSED,
	LIFT_ASCEND,
	LIFT_ARRIVED,
	LIFT_ENTER,
	LIFT_EXIT,
	UNLOCK_JETPACK,
    END_GAME,
	SENSITIVITY_CHANGED
}